version: 2.1
defaults: &defaults
  docker:
    - image: amazon/aws-cli

# Here the start of the exercise from the course:
jobs:
  create_and_deploy_front_end:
    <<: *defaults
    steps:
      - checkout
      - run: |
              aws cloudformation deploy \
                --template-file bucket.yml \
                --stack-name "eses-${CIRCLE_WORKFLOW_ID:0:7}" \
                --parameter-overrides PipelineID="eses-${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 cp index.html s3://eses-${CIRCLE_WORKFLOW_ID:0:7}/index.html

  get_last_deployment_id:
    <<: *defaults
    steps:
      - checkout
      - run: |
              aws cloudformation \
                list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
                --no-paginate --output text > ~/old_id.txt
              cat ~/old_id.txt
              yum install -y tar gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - old_id.txt
      # - save_cache:
      #     paths:
      #       - "~/old_id.txt"
      #     key: bucket-name

  promote_to_production:
    <<: *defaults
    steps:
      - checkout
      - run: |
              aws cloudformation deploy \
                --template-file cloudfront.yml \
                --stack-name production-distro \
                --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"

  clean_up_old_front_end:
    <<: *defaults
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - "bucket-name"
      - run: |
              yum install -y tar gzip
              PreviousPipelineID=`cat ~/old_id.txt`
              aws s3 rm "s3://${OldPipelineID}" --recursive
              aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
      - attach_workspace:
          at: ~/
workflows:
  create_and_deploy_front_end:
    # Run the welcome/run job in its own container
    jobs:
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires:
            - "create_and_deploy_front_end"
      - promote_to_production:
          requires:
            - "get_last_deployment_id"
      - clean_up_old_front_end:
          requires:
            - "promote_to_production"